# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BeanBagStub(object):
    """── RPCs ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/beanbag.BeanBag/CreateGame',
                request_serializer=game__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)
        self.JoinGame = channel.unary_unary(
                '/beanbag.BeanBag/JoinGame',
                request_serializer=game__pb2.JoinRequest.SerializeToString,
                response_deserializer=game__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.StartGame = channel.unary_unary(
                '/beanbag.BeanBag/StartGame',
                request_serializer=game__pb2.StartRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/beanbag.BeanBag/GetState',
                request_serializer=game__pb2.StateRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)
        self.PlayTurn = channel.unary_unary(
                '/beanbag.BeanBag/PlayTurn',
                request_serializer=game__pb2.TurnRequest.SerializeToString,
                response_deserializer=game__pb2.TurnResult.FromString,
                _registered_method=True)
        self.DiscardCard = channel.unary_unary(
                '/beanbag.BeanBag/DiscardCard',
                request_serializer=game__pb2.DiscardRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)
        self.SkipTurn = channel.unary_unary(
                '/beanbag.BeanBag/SkipTurn',
                request_serializer=game__pb2.SkipRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)
        self.DrawCards = channel.unary_unary(
                '/beanbag.BeanBag/DrawCards',
                request_serializer=game__pb2.DrawRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)
        self.LeaveGame = channel.unary_unary(
                '/beanbag.BeanBag/LeaveGame',
                request_serializer=game__pb2.LeaveRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)
        self.WatchGame = channel.unary_stream(
                '/beanbag.BeanBag/WatchGame',
                request_serializer=game__pb2.WatchRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)


class BeanBagServicer(object):
    """── RPCs ──────────────────────────────────────────────────────────────────

    """

    def CreateGame(self, request, context):
        """Lobby
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Gameplay
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscardCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkipTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrawCards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchGame(self, request, context):
        """Streaming — server pushes updates to all watchers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeanBagServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=game__pb2.CreateGameRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=game__pb2.JoinRequest.FromString,
                    response_serializer=game__pb2.JoinResponse.SerializeToString,
            ),
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=game__pb2.StartRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=game__pb2.StateRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'PlayTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayTurn,
                    request_deserializer=game__pb2.TurnRequest.FromString,
                    response_serializer=game__pb2.TurnResult.SerializeToString,
            ),
            'DiscardCard': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscardCard,
                    request_deserializer=game__pb2.DiscardRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'SkipTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.SkipTurn,
                    request_deserializer=game__pb2.SkipRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'DrawCards': grpc.unary_unary_rpc_method_handler(
                    servicer.DrawCards,
                    request_deserializer=game__pb2.DrawRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'LeaveGame': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGame,
                    request_deserializer=game__pb2.LeaveRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
            'WatchGame': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchGame,
                    request_deserializer=game__pb2.WatchRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beanbag.BeanBag', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beanbag.BeanBag', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BeanBag(object):
    """── RPCs ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/CreateGame',
            game__pb2.CreateGameRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/JoinGame',
            game__pb2.JoinRequest.SerializeToString,
            game__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/StartGame',
            game__pb2.StartRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/GetState',
            game__pb2.StateRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/PlayTurn',
            game__pb2.TurnRequest.SerializeToString,
            game__pb2.TurnResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscardCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/DiscardCard',
            game__pb2.DiscardRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SkipTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/SkipTurn',
            game__pb2.SkipRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrawCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/DrawCards',
            game__pb2.DrawRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beanbag.BeanBag/LeaveGame',
            game__pb2.LeaveRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beanbag.BeanBag/WatchGame',
            game__pb2.WatchRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
