# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import basic_pb2 as proto_dot_basic__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/basic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LobbyStub(object):
    """── RPCs ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/ctrlaltdefeat.Lobby/CreateGame',
                request_serializer=proto_dot_basic__pb2.CreateGameRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.GameState.FromString,
                _registered_method=True)
        self.JoinGame = channel.unary_unary(
                '/ctrlaltdefeat.Lobby/JoinGame',
                request_serializer=proto_dot_basic__pb2.JoinRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.StartGame = channel.unary_unary(
                '/ctrlaltdefeat.Lobby/StartGame',
                request_serializer=proto_dot_basic__pb2.StartRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.GameState.FromString,
                _registered_method=True)
        self.WatchGame = channel.unary_stream(
                '/ctrlaltdefeat.Lobby/WatchGame',
                request_serializer=proto_dot_basic__pb2.WatchRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.GameState.FromString,
                _registered_method=True)


class LobbyServicer(object):
    """── RPCs ──────────────────────────────────────────────────────────────────

    """

    def CreateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchGame(self, request, context):
        """Streaming — server pushes updates to all watchers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LobbyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=proto_dot_basic__pb2.CreateGameRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.GameState.SerializeToString,
            ),
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=proto_dot_basic__pb2.JoinRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.JoinResponse.SerializeToString,
            ),
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=proto_dot_basic__pb2.StartRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.GameState.SerializeToString,
            ),
            'WatchGame': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchGame,
                    request_deserializer=proto_dot_basic__pb2.WatchRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.GameState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ctrlaltdefeat.Lobby', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ctrlaltdefeat.Lobby', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Lobby(object):
    """── RPCs ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Lobby/CreateGame',
            proto_dot_basic__pb2.CreateGameRequest.SerializeToString,
            proto_dot_basic__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Lobby/JoinGame',
            proto_dot_basic__pb2.JoinRequest.SerializeToString,
            proto_dot_basic__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Lobby/StartGame',
            proto_dot_basic__pb2.StartRequest.SerializeToString,
            proto_dot_basic__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ctrlaltdefeat.Lobby/WatchGame',
            proto_dot_basic__pb2.WatchRequest.SerializeToString,
            proto_dot_basic__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/ctrlaltdefeat.Game/GetState',
                request_serializer=proto_dot_basic__pb2.StateRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.GameState.FromString,
                _registered_method=True)
        self.PlayTurn = channel.unary_unary(
                '/ctrlaltdefeat.Game/PlayTurn',
                request_serializer=proto_dot_basic__pb2.TurnRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.TurnResult.FromString,
                _registered_method=True)
        self.DiscardCard = channel.unary_unary(
                '/ctrlaltdefeat.Game/DiscardCard',
                request_serializer=proto_dot_basic__pb2.DiscardRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.GameState.FromString,
                _registered_method=True)
        self.SkipTurn = channel.unary_unary(
                '/ctrlaltdefeat.Game/SkipTurn',
                request_serializer=proto_dot_basic__pb2.SkipRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.GameState.FromString,
                _registered_method=True)
        self.DrawCards = channel.unary_unary(
                '/ctrlaltdefeat.Game/DrawCards',
                request_serializer=proto_dot_basic__pb2.DrawRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.DrawResult.FromString,
                _registered_method=True)
        self.LeaveGame = channel.unary_unary(
                '/ctrlaltdefeat.Game/LeaveGame',
                request_serializer=proto_dot_basic__pb2.LeaveRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.GameState.FromString,
                _registered_method=True)
        self.ResolveDiscard = channel.unary_unary(
                '/ctrlaltdefeat.Game/ResolveDiscard',
                request_serializer=proto_dot_basic__pb2.ResolveDiscardRequest.SerializeToString,
                response_deserializer=proto_dot_basic__pb2.DrawResult.FromString,
                _registered_method=True)


class GameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Gameplay
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscardCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkipTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrawCards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveDiscard(self, request, context):
        """Resolve a pending discard — see Player.pending_discard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=proto_dot_basic__pb2.StateRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.GameState.SerializeToString,
            ),
            'PlayTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayTurn,
                    request_deserializer=proto_dot_basic__pb2.TurnRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.TurnResult.SerializeToString,
            ),
            'DiscardCard': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscardCard,
                    request_deserializer=proto_dot_basic__pb2.DiscardRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.GameState.SerializeToString,
            ),
            'SkipTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.SkipTurn,
                    request_deserializer=proto_dot_basic__pb2.SkipRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.GameState.SerializeToString,
            ),
            'DrawCards': grpc.unary_unary_rpc_method_handler(
                    servicer.DrawCards,
                    request_deserializer=proto_dot_basic__pb2.DrawRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.DrawResult.SerializeToString,
            ),
            'LeaveGame': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGame,
                    request_deserializer=proto_dot_basic__pb2.LeaveRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.GameState.SerializeToString,
            ),
            'ResolveDiscard': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveDiscard,
                    request_deserializer=proto_dot_basic__pb2.ResolveDiscardRequest.FromString,
                    response_serializer=proto_dot_basic__pb2.DrawResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ctrlaltdefeat.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ctrlaltdefeat.Game', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Game/GetState',
            proto_dot_basic__pb2.StateRequest.SerializeToString,
            proto_dot_basic__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Game/PlayTurn',
            proto_dot_basic__pb2.TurnRequest.SerializeToString,
            proto_dot_basic__pb2.TurnResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscardCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Game/DiscardCard',
            proto_dot_basic__pb2.DiscardRequest.SerializeToString,
            proto_dot_basic__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SkipTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Game/SkipTurn',
            proto_dot_basic__pb2.SkipRequest.SerializeToString,
            proto_dot_basic__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrawCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Game/DrawCards',
            proto_dot_basic__pb2.DrawRequest.SerializeToString,
            proto_dot_basic__pb2.DrawResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Game/LeaveGame',
            proto_dot_basic__pb2.LeaveRequest.SerializeToString,
            proto_dot_basic__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveDiscard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ctrlaltdefeat.Game/ResolveDiscard',
            proto_dot_basic__pb2.ResolveDiscardRequest.SerializeToString,
            proto_dot_basic__pb2.DrawResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
